Build popover subcomponents
femmecubator/equity-ui pull request #37
Opened 2024-03-26 14:35 UTC by statsumi97

Worked on this on new branch:

https://trello.com/c/MffIDTs5/32-popover-build-subcomponents

MenuItem:

- Restored code from old branch
- Fixed styling to better match what's on Figma 

Divider:

- Restored code from old branch

Things to note:

- I know the icon should be different instead of copy-pasting an emoji. I couldn't remember how to use what's in the Icons component but will continue to work on this in the meantime. 

To QA: http://localhost:6006/?path=/story/menuitem--default

2024-03-26 17:46 UTC, vuonga1103 requested changes

2024-03-26 17:46 UTC, vuonga1103 commented on src/components/Divider/Divider.tsx
> +const Divider: React.FC<DividerProps> = () => {
i don't think the divider needs a variant prop bc it will always be one variant. 

we can just add type to props and prop-spread so that whatever HTML attribute we pass as props to `Divider` component gets also passed to `StyledDivider`

```javascript
const Divider = (props: React.HTMLAttributes<HTMLElement>) => {
  return <StyledDivider {...props} />;
};
```

& remove unnecessary interface `DividerProps`

2024-03-26 17:46 UTC, vuonga1103 commented on src/components/Divider/__docs__/Divider.stories.tsx
> +  argTypes: {
no need for argTypes since we don't really need any control or options for Divider. would revise to

```javascript
import React from 'react'
import type { Meta } from '@storybook/react';
import Divider from '../Divider';

const meta: Meta<typeof Divider> = {
  title: 'Divider',
  component: Divider,
};

export default meta;

export const Default = {
  render: (args) => <Divider {...args} />,
};
```

2024-03-26 17:46 UTC, vuonga1103 commented on src/components/MenuItem/MenuItem.tsx
> +      className={`menu-item ${disabled ? 'disabled' : ''}`}
instead of using className, could we pass disabled as props into `StyledButton` and use it within a callback in the styled component?

2024-03-26 17:46 UTC, vuonga1103 commented on src/components/MenuItem/MenuItem.tsx
> +    color: var(--color-content-brand, #026fe4);
where possible could we pull token vars from `theme`?

2024-03-26 17:46 UTC, vuonga1103 commented on src/components/index.ts
> +export * from './SectionTitle';
need an export for `Divider`

2024-03-26 22:48 UTC, statsumi97 commented
I have pushed the updated code which addresses the following: 

- Removed variant prop and unnecessary interface DividerProps
- removed argTypes
- Passed disabled as props into StyledButton
- Pulled token vars from theme
- Exported Divider, MenuItem and Popover into Index.ts

I have also pushed code for the Popover. 

Trello:
https://trello.com/c/MffIDTs5/32-popover-build-subcomponents
https://trello.com/c/QlXzcs1E/36-popover-build-popover

To QA: http://localhost:6006/?path=/story/menuitem--disabled

2024-03-27 13:35 UTC, statsumi97 commented
Pushed code which adds dynamic icons. 

For QA: http://localhost:6006/?path=/story/menuitem--disabled

2024-03-27 14:40 UTC, vuonga1103 requested changes
great job on this! requesting the following changes. i would prioritize things in the following order:
1. addressing all comments except the one about rendering popover on a portal
2. start looking into how you may want to test these components
3. work on the portal problem

feel free to comment on each of the thread below if you need additional clarification.

oh also, no need to relink the storybook localhost and trello links! :D

2024-03-27 14:40 UTC, vuonga1103 commented on src/components/MenuItem/MenuItem.tsx
> +  width: 191px;
setting a fixed width might give rise to visual bugs, typically you want to do 100% to fit the size of whatever container the menu item is in

2024-03-27 14:40 UTC, vuonga1103 commented on src/components/MenuItem/MenuItem.tsx
> +  ${({ theme, disabled }) => `
could destructure out some theme vars so we don't have to use `theme.base....` each time we use a design token. 

could you use destructuring so that we can do... `spacing.spacing4`, `border.radius.radius4`, etc.?

2024-03-27 14:40 UTC, vuonga1103 commented on src/components/MenuItem/MenuItem.tsx
> +const MenuItem: React.FC<MenuItemProps> = ({
if we want to use the menu item without an icon, how would we be able to do that?

2024-03-27 14:40 UTC, vuonga1103 commented on src/components/MenuItem/MenuItem.tsx
> +      onFocus={() => console.log('focus')}
might be unnecessary to add event handlers. we would ideally want to leave these for the users to configure on a case to case basis. 

additionally always make sure that `{...props}` comes last. otherwise whatever the user adds might get overridden.

2024-03-27 14:40 UTC, vuonga1103 commented on src/components/MenuItem/__docs__/MenuItem.stories.tsx
> +import type { Meta, StoryObj } from '@storybook/react';
a few storybook related things:
1. icon size control is text right now so the SB-viewer would be able to type in anything. how can we constrict this control to only allow the user to select one of the available icon sizes?

https://github.com/femmecubator/equity-ui/assets/58869812/dd83fba3-1d4b-413b-a3ca-fe74b258361c

3. could we have a story for a no-icon variation of the component? 

4. when i add text that is very long - the icon progressively gets smaller and ultimately disappears. let's address that. 

https://github.com/femmecubator/equity-ui/assets/58869812/4ddeb82f-dc4e-4a0f-9e43-17b9afb4394c

2024-03-27 14:40 UTC, vuonga1103 commented on src/components/MenuItem/MenuItem.tsx
> +      disabled={disabled}
for accessibility reasons we should add `role="menuitem"`

read more here https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/menuitem_role

2024-03-27 14:40 UTC, vuonga1103 commented on src/components/Popover/Popover.tsx
> +const Popover: React.FC<PopoverProps> = ({ open, anchorElement, children }) => {
we need to figure out how to render the popover in a portal. 

> Portals render parts of a React component tree into a different part of the DOM. This is useful for UI components that need to appear over the top of other components, such as modal dialog, flag and tooltip.

2024-03-27 14:40 UTC, vuonga1103 commented on src/components/Popover/Popover.tsx
> +const Popover: React.FC<PopoverProps> = ({ open, anchorElement, children }) => {
https://react.dev/reference/react-dom/createPortal

2024-03-27 14:40 UTC, vuonga1103 commented on src/components/Popover/Popover.tsx
> +  width: 227px;
would we want the popover to have this width always? or should it be more dynamic? perhaps we can set a min-width?

2024-03-27 14:40 UTC, vuonga1103 commented on src/components/Popover/Popover.tsx
> +const Popover: React.FC<PopoverProps> = ({ open, anchorElement, children }) => {
^ this is the part that i feel like will take longer - hence wanting to focus on the build of the subcomponents. i'd say for you to focus on addressing the other subcomponents' comments before heading to this.

2024-03-27 14:40 UTC, vuonga1103 commented on src/components/Popover/Popover.tsx
> +  border-radius: var(--border-radius-default, 16px);
previous comments re: use of tokens apply here.

2024-03-27 14:40 UTC, vuonga1103 commented on src/components/Popover/Popover.tsx
> +  return <StyledPopover position={position}>{children}</StyledPopover>;
what role can we assign to this to make it more accessible?

2024-03-27 14:40 UTC, vuonga1103 commented on src/components/Popover/Popover.tsx
> +const Popover: React.FC<PopoverProps> = ({ open, anchorElement, children }) => {
would the user be able to pass other attributes to the popover? how may they be able to do that?

2024-03-27 14:40 UTC, vuonga1103 commented on src/components/Divider/Divider.tsx
> +// Styled divider using styled-components for styling
let’s remove unnecessary comments (totally understand that you use these for learning purposes, but for production code, we should use comments extremely sparingly and write code in such a way that it’d be self-explanatory). 

applies to this and wherever else in the PR

2024-03-29 21:18 UTC, ctrl-alt-delete007 commented on src/components/MenuItem/__docs__/MenuItem.stories.tsx
> +  },
if you find yourself repeating codes, write a function for it

2024-03-29 21:18 UTC, ctrl-alt-delete007 commented on src/components/MenuItem/__docs__/MenuItem.stories.tsx
> +    iconColor: 'default',
x2

2024-03-29 21:18 UTC, ctrl-alt-delete007 commented on src/components/MenuItem/__docs__/MenuItem.stories.tsx
> +    iconColor: 'default',
x3

2024-03-29 21:18 UTC, ctrl-alt-delete007 commented on src/components/MenuItem/__docs__/MenuItem.stories.tsx
> +    iconColor: 'default',
x4

2024-03-29 21:18 UTC, ctrl-alt-delete007 commented on src/components/SectionTitle/SectionTitle.tsx
> +  line-height: 22px;
let's move this down and apply theme

2024-04-04 14:44 UTC, vuonga1103 commented on src/components/MenuItem/__docs__/MenuItem.stories.tsx
> +function createMenuItemArgs({
use `menuItemArgs` object in place of function

2024-04-04 14:44 UTC, vuonga1103 commented on src/components/MenuItem/__docs__/MenuItem.stories.tsx
> +  iconColor = 'default' as IconColor,
add `noIcon` prop to deal with no icons

2024-04-04 14:44 UTC, vuonga1103 commented on src/components/MenuItem/MenuItem.tsx
> +  onMouseEnter = () => console.log('hover'),
can remove handler props

2024-04-04 14:44 UTC, vuonga1103 commented on src/components/MenuItem/MenuItem.test.tsx
> +const customRender = (
use `contextRender`

2024-04-04 14:44 UTC, vuonga1103 commented on src/components/MenuItem/MenuItem.test.tsx
> +  it('should render correctly', () => {
add render tests for other subcomponents

2024-04-04 14:44 UTC, vuonga1103 commented on src/components/MenuItem/MenuItem.tsx
> +      /* body/small */
unnecessary comment

2024-04-04 14:44 UTC, vuonga1103 commented on src/components/MenuItem/MenuItem.tsx
> +        padding-right: 95px;
let's remove this hardcode of 95px

2024-04-04 14:44 UTC, vuonga1103 commented on src/components/MenuItem/MenuItem.tsx
> +const MenuItem: React.FC<MenuItemProps> = ({
nice to have - vertical alignment of icon & text 
<img width="182" alt="image" src="https://github.com/femmecubator/equity-ui/assets/58869812/bbc7c0f9-3bdb-4fcd-b76b-3a1574e4b096">

2024-04-04 14:44 UTC, vuonga1103 commented on src/components/MenuItem/MenuItem.tsx
> +      <span
nit - create styled component

2024-04-04 21:12 UTC, vuonga1103 approved these changes

2024-04-04 21:12 UTC, vuonga1103 commented on src/components/MenuItem/MenuItem.test.tsx
> +const contextRender = (
use our `contextRender` from src/shared/utils/contextRender.tsx

2024-04-04 21:12 UTC, vuonga1103 commented on src/components/SectionTitle/SectionTitle.test.tsx
> +const contextRender = (ui: React.ReactElement) => {
use contextRender from `src/shared/utils/contextRender.tsx`

2024-04-04 21:23 UTC, merged